# ==============================================================
# = Pincio Web Service
# ==============================================================

spring:
  application:
    name: PincioBotService
    

  

