# ==============================================================
# = Pincio Web Service
# ==============================================================

bot:
  token: test
  username: test

spring:
  application:
    name: PincioBotService
    

  

